<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Plan de pruebas" duration-ms="0" started-at="2018-03-12T05:19:59Z" finished-at="2018-03-12T05:19:59Z">
    <groups>
    </groups>
  </suite> <!-- Plan de pruebas -->
  <suite name="Pruebas de Aritmetica" duration-ms="298" started-at="2018-03-12T05:19:58Z" finished-at="2018-03-12T05:19:58Z">
    <groups>
    </groups>
    <test name="Prueba de operaciones basicas" duration-ms="298" started-at="2018-03-12T05:19:58Z" finished-at="2018-03-12T05:19:58Z">
      <class name="PracticaEclipse.Unitarias.AritmeticaTest">
        <test-method status="PASS" signature="setUp(int, int)[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@54cf7c6a]" name="setUp" is-config="true" duration-ms="48" started-at="2018-03-11T23:19:58Z" finished-at="2018-03-11T23:19:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testDivision()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@54cf7c6a]" name="testDivision" duration-ms="30" started-at="2018-03-11T23:19:58Z" finished-at="2018-03-11T23:19:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDivision -->
        <test-method status="PASS" signature="testMultiplicacion()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@54cf7c6a]" name="testMultiplicacion" duration-ms="5" started-at="2018-03-11T23:19:58Z" finished-at="2018-03-11T23:19:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMultiplicacion -->
        <test-method status="FAIL" signature="testMultiplicacion2()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@54cf7c6a]" name="testMultiplicacion2" duration-ms="133" started-at="2018-03-11T23:19:58Z" finished-at="2018-03-11T23:19:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[No da el mismo resultado se esperaba: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: No da el mismo resultado se esperaba: 4
	at org.testng.Assert.fail(Assert.java:94)
	at PracticaEclipse.Unitarias.AritmeticaTest.testMultiplicacion2(AritmeticaTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMultiplicacion2 -->
        <test-method status="PASS" signature="testResta()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@54cf7c6a]" name="testResta" duration-ms="6" started-at="2018-03-11T23:19:58Z" finished-at="2018-03-11T23:19:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResta -->
        <test-method status="PASS" signature="testSuma()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@54cf7c6a]" name="testSuma" duration-ms="6" started-at="2018-03-11T23:19:58Z" finished-at="2018-03-11T23:19:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuma -->
        <test-method status="PASS" signature="setOut()[pri:0, instance:PracticaEclipse.Unitarias.AritmeticaTest@54cf7c6a]" name="setOut" is-config="true" duration-ms="0" started-at="2018-03-11T23:19:58Z" finished-at="2018-03-11T23:19:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setOut -->
      </class> <!-- PracticaEclipse.Unitarias.AritmeticaTest -->
    </test> <!-- Prueba de operaciones basicas -->
  </suite> <!-- Pruebas de Aritmetica -->
</testng-results>
